import './globals.css'
import NavbarComponent from '../components/NavbarComponent'

export const metadata = {
  title: 'Nutrición Clínica - Ana Karen Juárez',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <NavbarComponent/>
        {children}
      </body>
    </html>
  )
}
