
  export const verduras = [
    {nombre:'Acelga cocida', equivalente: '1/2 taza', gramos: 70},
    {nombre:'Apio crudo', equivalente: '1 taza', gramos: 90},
    {nombre:'Apio cocido', equivalente: '1/2 taza', gramos: 75},
    {nombre:'Brócoli cocido', equivalente: '1/2 taza', gramos: 90},
    {nombre:'Brócoli crudo', equivalente: '1 taza', gramos: 70},
    {nombre:'Calabaza cocida', equivalente: '1/2 taza', gramos: 110},
    {nombre:'Cebolla cruda', equivalente: '1/2 taza', gramos: 60},
    {nombre:'Cebolla cocida', equivalente: '1/4 taza', gramos: 50},
    {nombre:'Champiñón cocido', equivalente: '1/2 taza', gramos: 70},
    {nombre:'Champiñón crudo', equivalente: '1 taza', gramos: 90},
    {nombre:'Chayote cocido', equivalente: '1/2 taza', gramos: 80},    
    {nombre:'Chícharo cocido', equivalente: '1/4 taza', gramos: 40},
    {nombre:'Chile jalapeño', equivalente: '6 piezas', gramos: 80},
    {nombre:'Chile morita', equivalente: '7 gramos', gramos: 7},
    {nombre:'Chile serrano', equivalente: '56 gramos', gramos: 56},
    {nombre:'Col cruda', equivalente: '2 tazas', gramos: 140},
    {nombre:'Coliflor cocida', equivalente: '1 taza', gramos: 125},
    {nombre:'Ejotes cocidos', equivalente: '1/2 taza', gramos: 60},
    {nombre:'Espárragos', equivalente: '6 piezas', gramos: 90},
    {nombre:'Espinaca cruda', equivalente: '2 tazas', gramos: 120},
    {nombre:'Espinaca cocida', equivalente: '1/2 taza', gramos: 90},
    {nombre:'Germen de alfalfa crudo', equivalente: '3 tazas', gramos: 100},
    {nombre:'Germen de lenteja crudo', equivalente: '1/4 taza', gramos: 20},
    {nombre:'Germen de soya cocido', equivalente: '1/3 taza', gramos: 30},
    {nombre:'Germinado de lenteja', equivalente: '1/2 taza', gramos: 20},
    {nombre:'Hongo portobello crudo', equivalente: '1 pieza', gramos: 80},
    {nombre:'Jícama picada', equivalente: '1/2 taza', gramos: 60},
    {nombre:'Lechuga', equivalente: '3 tazas', gramos: 140},
    {nombre:'Nopal cocido', equivalente: '1 taza', gramos: 150},
    {nombre:'Nopal crudo', equivalente: '2 piezas', gramos: 140},
    {nombre:'Pepinillo crudo', equivalente: '1/3 taza', gramos: 80},
    {nombre:'Pimiento', equivalente: '1 pieza', gramos: 70},
    {nombre:'Tomate rojo', equivalente: '1 pieza', gramos: 120},
    {nombre:'Tomate verde', equivalente: '5 piezas', gramos: 90},
    {nombre:'Trigo germinado', equivalente: '1/7 taza', gramos: 10},
    {nombre:'Verdolaga cocida', equivalente: '1 taza', gramos: 115},
    {nombre:'Zanahoria cruda', equivalente: '1/2 taza', gramos: 65},
  ];

  export const frutas = [
    {nombre:'Arándano fresco', equivalente: '1 1/2 taza', gramos: 150},
    {nombre:'Blueberries', equivalente: '3/4 taza', gramos: 110},
    {nombre:'Blueberries congeladas con azúcar', equivalente: '1/4 taza', gramos: 60},
    {nombre:'Cereza', equivalente: '20 piezas', gramos: 90},
    {nombre:'Cereza en almíbar', equivalente: '1/4 taza', gramos: 60},
    {nombre:'Chabacano', equivalente: '4 piezas', gramos: 125},
    {nombre:'Ciruela pasa sin hueso', equivalente: '7 piezas', gramos: 55},
    {nombre:'Dátil seco', equivalente: '2 piezas', gramos: 20},
    {nombre:'Durazno amarillo', equivalente: '2 piezas', gramos: 150},
    {nombre:'Durazno almíbar', equivalente: '1/2 taza', gramos: 130},
    {nombre:'Frambuesa', equivalente: '1 taza', gramos: 120},
    {nombre:'Fresa', equivalente: '1 taza', gramos: 170},
    {nombre:'Fruta picada', equivalente: '1 taza', gramos: 140},
    {nombre:'Guayaba', equivalente: '3 piezas', gramos: 120},
    {nombre:'Higo', equivalente: '2 piezas', gramos: 70},
    {nombre:'Higo deshidratado', equivalente: '1 piezas', gramos: 20},
    {nombre:'Jugo de limón', equivalente: '3/4 taza', gramos: 180},
    {nombre:'Jugo de mandarina natural', equivalente: '1/2 taza', gramos: 120},
    {nombre:'Jugo de mango', equivalente: '1/2 taza', gramos: 120},
    {nombre:'Jugo de manzana', equivalente: '1/2 taza', gramos: 120},
    {nombre:'Jugo de naranja natural', equivalente: '1/2 taza', gramos: 120},
    {nombre:'Jugo de papaya', equivalente: '1/3 taza', gramos: 80},
    {nombre:'Jugo de piña natural', equivalente: '1/2 taza', gramos: 120},
    {nombre:'Jugo de toronja natural', equivalente: '1/2 taza', gramos: 120},
    {nombre:'Kiwi', equivalente: '1 1/2 pieza', gramos: 115},
    {nombre:'Lima', equivalente: '3 piezas', gramos: 150},
    {nombre:'Limón real', equivalente: '4 piezas', gramos: 150},
    {nombre:'Mamey', equivalente: '1/3 pieza', gramos: 85},
    {nombre:'Mandarina', equivalente: '2 pieza', gramos: 130},
    {nombre:'Mango picado', equivalente: '1 taza', gramos: 170},
    {nombre:'Manzana', equivalente: '1 pieza', gramos: 110},
    {nombre:'Manzana al vapor', equivalente: '1/2 taza', gramos: 90},
    {nombre:'Manzana cocida', equivalente: '1/2 taza', gramos: 90},
    {nombre:'Manzana deshidratada', equivalente: '9 orejones', gramos: 25},
    {nombre:'Manzana almíbar', equivalente: '1 pieza', gramos: 25},
    {nombre:'Manzana picada', equivalente: '1/2 taza', gramos: 75},
    {nombre:'Manzana verde', equivalente: '1/2 pieza', gramos: 71},
    {nombre:'Melón', equivalente: '1/3 pieza', gramos: 180},
    {nombre:'Melón chino', equivalente: '1/4 pieza', gramos: 145},
    {nombre:'Melón picado', equivalente: '1 taza', gramos: 160},
    {nombre:'Melón chino', equivalente: '1/4 pieza', gramos: 145},
    {nombre:'Melón verde picado', equivalente: '1 taza', gramos: 160},
    {nombre:'Naranja', equivalente: '2 piezas', gramos: 150},
    {nombre:'Naranja sin semilla', equivalente: '1 pieza', gramos: 150},
    {nombre:'Nectarina', equivalente: '1 pieza', gramos: 125},
    {nombre:'Papaya picada', equivalente: '1 taza', gramos: 140},
    {nombre:'Pasas', equivalente: '10 piezas', gramos: 20},
    {nombre:'Pera', equivalente: '1/2 pieza', gramos: 80},
    {nombre:'Piña en almíbar', equivalente: '1/3 taza', gramos: 63},
    {nombre:'Piña picada', equivalente: '3/4 taza', gramos: 125},
    {nombre:'Plátano', equivalente: '1/2 pieza', gramos: 55},
    {nombre:'Plátano deshidratado', equivalente: '1/4 taza', gramos: 20},
    {nombre:'Plátano dominico', equivalente: '3 piezas', gramos: 60},
    {nombre:'Plátano macho', equivalente: '1/4 pieza', gramos: 50},
    {nombre:'Sandía picada', equivalente: '1 taza', gramos: 160},
    {nombre:'Sandía rebanada', equivalente: '1 taza', gramos: 200},
    {nombre:'Tamarindo', equivalente: '50 gramos', gramos: 50},
    {nombre:'Tamarindo pulpa sin azúcar', equivalente: '8 cdas', gramos: 100},
    {nombre:'Tamarindo pelado', equivalente: '1/4 taza', gramos: 30},
    {nombre:'Tejocote', equivalente: '2 piezas', gramos: 60},
    {nombre:'Toronja', equivalente: '1 pieza', gramos: 162},
    {nombre:'Tuna', equivalente: '2 pieza', gramos: 140},
    {nombre:'Uva', equivalente: '18 piezas', gramos: 90},
  ];

  export const leguminosas = [
    {nombre:'Frijol cocido', equivalente: '1/2 taza', gramos: 100},
    {nombre:'Frijol molido', equivalente: '1/3 taza', gramos: 75},
    {nombre:'Frijol entero de lata', equivalente: '1/2 taza', gramos: 130},
    {nombre:'Frijol refrito, casero o enlatado', equivalente: '40g', gramos: 40},
    {nombre:'Garbanzo cocido', equivalente: '1/2 taza', gramos: 80},
    {nombre:'Garbanzo enlatado', equivalente: '1/2 taza', gramos: 120},
    {nombre:'Hummus', equivalente: '5 cda', gramos: 75},
    {nombre:'Lenteja cocida', equivalente: '1/2 taza', gramos: 100},
    {nombre:'Soya cocida', equivalente: '1/3 taza', gramos: 60},
    {nombre:'Soya texturizada', equivalente: '30g', gramos: 30},
  ];
